apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespaceprotects.hj.com
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: $ca
#    url: https://$ip:8443/validate-ns
    service:
      name: $svc
      namespace: $ns
      path: /validate-ns
      port: 443
  namespaceSelector:
    matchExpressions:
    - key: 'kubernetes.io/metadata.name'
      operator: NotIn
      values:
      - kube-system
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-namespace.namespaceprotects.hj.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
    scope: '*'
  sideEffects: None #NoneOnDryRun
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: $ca
#    url: https://$ip:8443/validate-np-params
    service:
      name: $svc_name
      namespace: $ns_name
      path: /validate-np-params
      port: 443
  namespaceSelector:
    matchExpressions:
      - key: 'kubernetes.io/metadata.name'
        operator: NotIn
        values:
          - kube-system
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-np-params.namespaceprotects.hj.com
  rules:
  - apiGroups:
    - hj.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaceprotects
    scope: '*'
  sideEffects: None #NoneOnDryRun
  timeoutSeconds: 30