kubectl apply -f - <<e
apiVersion: hj.com/v1
kind: NamespaceProtect
metadata:
  name: test
spec:
  namespaces:
#  - 'default'
  - 't1'
#  selectors:
#    labels:
#      app: xx
  protectSubresources: false
e