apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceprotects.hj.com
spec:
  scope: Cluster
  group: hj.com
  names:
    kind: NamespaceProtect
    plural: namespaceprotects
    singular: namespaceprotect
    shortNames:
    - np
    - nps
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              namespaces:
                type: array
                items:
                  type: string
              selectors:
                type: object
                properties:
                  labels:
                    type: object
#            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true