---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: np-operator
rules:
  - apiGroups: [hj.com]
    resources: [namespaceprotects]
    verbs: ['*']
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: ["",apps]
    resources: [namespaces,configmaps,secrets,services,deployments,statefulsets]
    verbs: [list, watch,update,patch]
  - apiGroups: [admissionregistration.k8s.io, admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch,update,list,watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: np-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: np-operator
subjects:
- kind: ServiceAccount
  name: np-operator
  namespace: np-operator
- kind: ServiceAccount
  name: np-webhook
  namespace: np-operator
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: np-operator
#rules:
#  - apiGroups: [ hj.com ]
#    resources: [ namespaceprotects ]
#    verbs: [ '*' ]
#  - apiGroups: [""]
#    resources: [events]
#    verbs: [create]
#  - apiGroups: [batch, extensions]
#    resources: [jobs]
#    verbs: [create]
#  - apiGroups: [""]
#    resources: [pods, persistentvolumeclaims]
#    verbs: [create]
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: np-operator
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: np-operator
#subjects:
#  - kind: ServiceAccount
#    name: np-operator