apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-operator
  namespace: np-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: np-operator
  template:
    metadata:
      labels:
        app: np-operator
    spec:
      serviceAccountName: np-operator
      containers:
      - name: np-operator
        image: registry.cn-hangzhou.aliyuncs.com/suyanhj/namespace-protect-operator:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: env
          value: "k8s"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
